### ISSUE TITLE
Gdown is no longer working and Google drive download is very unstable 

### ISSUE THREAD

**Issue by bermudezarii** [henghuiding/MOSE-api#1]
Hello! 

We appreciate the release of this dataset! It's fantastic. 
I would like just to point out that gdown is showing this error: 

`gdown https://drive.google.com/uc\?id\=10HYO-CJTaITalhzl_Zbz_Qpesh8F3gZR
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=10HYO-CJTaITalhzl_Zbz_Qpesh8F3gZR 
`
And when you download from Google Drive it breaks every 2 min and eventually is a failed download. Besides, in Baidu, it shows errors to download. The most stable so far is One Drive. 

Thanks.

**Comment by ntuLC** [comment]
Hi,

Thanks for your interest and feedback! We have updated the gdown command for better CLI compatibility. 

However, sometimes the gdown command may still be unavailable because of the limitations of Google Drive. You can try to download from the Google Drive page with an google account, which may improve the downloading speed from our experience😀

Thanks!
